name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/jisbert/6-player-clock:1.0.2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake for Coverage
      run: cmake -B ${{ github.workspace }}/coverage -DENABLE_COVERAGE=ON

    - name: Build Coverage (runs tests)
      run: cmake --build ${{ github.workspace }}/coverage --target coverage
