name: CMake

on: [push]

env:
  PICO_SDK_PATH: /pico-sdk
  PICO_SDK_VERSION: '1.5.0'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/jisbert/6-player-clock:1.0.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/coverage -DENABLE_COVERAGE=ON -GNinja -DCMAKE_MAKE_PROGRAM=/usr/lib/ninja-build/bin/ninja
      # cmake -S . -B build -DENABLE_TESTS=OFF -DENABLE_COVERAGE=OFF -GNinja -DCMAKE_MAKE_PROGRAM=/usr/lib/ninja-build/bin/ninja

    - name: Build Tests and Coverage
      run: cmake --build ${{ github.workspace }}/coverage --target coverage
