name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/jisbert/pico-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Code coverage report
      run: |
        cmake -B ${{ github.workspace }}/coverage -DENABLE_COVERAGE=ON
        cmake --build ${{ github.workspace }}/coverage --target coverage

    - name: Archive code coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: |
          ${{ github.workspace }}/coverage/coverage
          !${{ github.workspace }}/coverage/coverage/src
          !${{ github.workspace }}/coverage/coverage/tests

    - name: Production binaries
      run: |
        cmake -B ${{ github.workspace }}/build -DENABLE_TESTS=OFF
        cmake --build ${{ github.workspace }}/build --target 6_player_clock

    - name: Archive production binaries
      uses: actions/upload-artifact@v3
      with:
        name: production-binaries
        path: |
          ${{ github.workspace }}/build/*.elf
          ${{ github.workspace }}/build/*.uf2
