name: CMake

on: [push]

env:
  PICO_SDK_PATH: /pico-sdk
  PICO_SDK_VERSION: '1.5.0'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/jisbert/6-player-clock:1.0.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DENABLE_COVERAGE=ON

    - name: Build Tests and Coverage
      run: cmake --build ${{ github.workspace }}/build --target coverage
