name: CMake

on: [push]

env:
  PICO_SDK_PATH: pico/pico-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake for Tests
      run: cmake -B ${{github.workspace}}/build -DENABLE_TESTS=ON

    - name: Build for Tests
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: tests/tests
