name: CMake

on: [push]

env:
  PICO_SDK_RELATIVE_PATH: lib/pico/pico-sdk
  PICO_SDK_PATH: ${{ github.workspace }}/${{ env.PICO_SDK_RELATIVE_PATH }}
  PICO_SDK_VERSION: '1.5.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Raspberry Pi Pico C/C++ SDK
      uses: actions/cache@v3
      with:
        path: lib
        key: ${{ runner.os }}-build-pico-sdk-${{ env.PICO_SDK_VERSION }}
        restore-keys: |
          ${{ runner.os }}-build-pico-sdk-
          ${{ runner.os }}-

    - name: Checkout Pico SDK repository
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-sdk
        ref: ${{ env.PICO_SDK_VERSION }}
        path: ${{ env.PICO_SDK_RELATIVE_PATH }}
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DENABLE_COVERAGE=ON
      env:
        PICO_TOOLCHAIN_PATH: bin

    - name: Build Tests and Coverage
      run: cmake --build ${{ github.workspace }}/build --target coverage
